// data.js

// 1. CONFIGURATION
// This maps internal IDs to the labels and icon files in your 'icons/' folder
const mapConfig = {
    groups: {
        exploration: { title: "Exploration", expanded: true },
        combat: { title: "Combat", expanded: true },
        quests: { title: "Quests & Collectibles", expanded: true }
    },
    types: {
        // EXPLORATION
        bench:      { group: "exploration", label: "Bench", icon: "icons/bench.png" },
        bellway:    { group: "exploration", label: "Bellway", icon: "icons/bellway.png" },
        ventrica:   { group: "exploration", label: "Ventrica", icon: "icons/ventrica.png" },
        vendor:     { group: "exploration", label: "Vendor", icon: "icons/vendor.png" },
        map:        { group: "exploration", label: "Map Tool", icon: "icons/map.png" },
        boss:       { group: "exploration", label: "Boss", icon: "icons/boss.png" },
        key:        { group: "exploration", label: "Key / Gate", icon: "icons/key_and_gate.png" },

        // COMBAT
        ability:    { group: "combat", label: "Ability", icon: "icons/ability.png" },
        mask:       { group: "combat", label: "Mask Shard", icon: "icons/mask_shard.png" },
        silkheart:  { group: "combat", label: "Silk Heart", icon: "icons/silk_heart.png" },
        spool:      { group: "combat", label: "Spool Fragment", icon: "icons/spool_fragment.png" },
        memory:     { group: "combat", label: "Memory Locket", icon: "icons/memory_locket.png" },
        crest:      { group: "combat", label: "Crest", icon: "icons/chrest.png" }, // Using 'chrest.png' as per your file list
        tool:       { group: "combat", label: "Tool", icon: "icons/tool.png" },
        skill:      { group: "combat", label: "Skill", icon: "icons/skill.png" },

        // QUESTS & COLLECTIBLES
        wish:       { group: "quests", label: "Wish", icon: "icons/wish.png" },
        flea:       { group: "quests", label: "Lost Flea", icon: "icons/lost_flea.png" },
        craftmetal: { group: "quests", label: "Craftmetal", icon: "icons/craft_metal.png" },
        mossberry:  { group: "quests", label: "Mossberry", icon: "icons/mossberry.png" },
        pollip:     { group: "quests", label: "Pollip Flower", icon: "icons/pollip_flower.png" },
        flint:      { group: "quests", label: "Flintbeetle", icon: "icons/flintbeetle.png" },
        delicacy:   { group: "quests", label: "Delicacy", icon: "icons/delicacy.png" },
        cogheart:   { group: "quests", label: "Cogheart", icon: "icons/cogheart.png" },
        plasmium:   { group: "quests", label: "Plasmium", icon: "icons/plasmium.png" }
    }
};

// 2. MAP DATA
// This is where you will paste the JSON generated by the "Admin Mode".
// Example data included below to test if it works.
const mapData = [
    //Bench:::
    {
        "id": "bench_1410_3922",
        "type": "bench",
        "x": 1410,
        "y": 3922,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_447_3175",
        "type": "bench",
        "x": 447,
        "y": 3175,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_1360_3490",
        "type": "bench",
        "x": 1360,
        "y": 3490,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_1337_3021",
        "type": "bench",
        "x": 1337,
        "y": 3021,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_1562_3492",
        "type": "bench",
        "x": 1562,
        "y": 3492,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_1656_3419",
        "type": "bench",
        "x": 1656,
        "y": 3419,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_1846_3279",
        "type": "bench",
        "x": 1846,
        "y": 3279,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_1708_3027",
        "type": "bench",
        "x": 1708,
        "y": 3027,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_2434_3396",
        "type": "bench",
        "x": 2434,
        "y": 3396,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_3040_3461",
        "type": "bench",
        "x": 3040,
        "y": 3461,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_2546_3098",
        "type": "bench",
        "x": 2546,
        "y": 3098,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_2982_3152",
        "type": "bench",
        "x": 2982,
        "y": 3152,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_3218_4439",
        "type": "bench",
        "x": 3218,
        "y": 4439,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_3463_4022",
        "type": "bench",
        "x": 3463,
        "y": 4022,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_3540_3481",
        "type": "bench",
        "x": 3540,
        "y": 3481,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_3933_3376",
        "type": "bench",
        "x": 3933,
        "y": 3376,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_3859_3376",
        "type": "bench",
        "x": 3859,
        "y": 3376,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_4917_3509",
        "type": "bench",
        "x": 4917,
        "y": 3509,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_5550_3316",
        "type": "bench",
        "x": 5550,
        "y": 3316,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_5280_2954",
        "type": "bench",
        "x": 5280,
        "y": 2954,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_4891_3217",
        "type": "bench",
        "x": 4891,
        "y": 3217,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_530_2954",
        "type": "bench",
        "x": 530,
        "y": 2954,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_584_2240",
        "type": "bench",
        "x": 584,
        "y": 2240,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_1218_2389",
        "type": "bench",
        "x": 1218,
        "y": 2389,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_1699_2526",
        "type": "bench",
        "x": 1699,
        "y": 2526,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_1832_2722",
        "type": "bench",
        "x": 1832,
        "y": 2722,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_2526_2765",
        "type": "bench",
        "x": 2526,
        "y": 2765,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_2322_2310",
        "type": "bench",
        "x": 2322,
        "y": 2310,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_2783_2608",
        "type": "bench",
        "x": 2783,
        "y": 2608,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_3068_2956",
        "type": "bench",
        "x": 3068,
        "y": 2956,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_3182_3360",
        "type": "bench",
        "x": 3182,
        "y": 3360,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_4122_3210",
        "type": "bench",
        "x": 4122,
        "y": 3210,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_4260_2926",
        "type": "bench",
        "x": 4260,
        "y": 2926,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_3714_2926",
        "type": "bench",
        "x": 3714,
        "y": 2926,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_4574_3299",
        "type": "bench",
        "x": 4574,
        "y": 3299,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_729_1535",
        "type": "bench",
        "x": 729,
        "y": 1535,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_1025_1024",
        "type": "bench",
        "x": 1025,
        "y": 1024,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_1175_1026",
        "type": "bench",
        "x": 1175,
        "y": 1026,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_1491_1097",
        "type": "bench",
        "x": 1491,
        "y": 1097,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_1621_1311",
        "type": "bench",
        "x": 1621,
        "y": 1311,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_1724_1401",
        "type": "bench",
        "x": 1724,
        "y": 1401,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_1404_1699",
        "type": "bench",
        "x": 1404,
        "y": 1699,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_1615_1903",
        "type": "bench",
        "x": 1615,
        "y": 1903,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_1156_1987",
        "type": "bench",
        "x": 1156,
        "y": 1987,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_1894_1523",
        "type": "bench",
        "x": 1894,
        "y": 1523,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_2068_1347",
        "type": "bench",
        "x": 2068,
        "y": 1347,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_2750_1675",
        "type": "bench",
        "x": 2750,
        "y": 1675,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_2786_1805",
        "type": "bench",
        "x": 2786,
        "y": 1805,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_3152_1673",
        "type": "bench",
        "x": 3152,
        "y": 1673,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_3407_2141",
        "type": "bench",
        "x": 3407,
        "y": 2141,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_3320_2592",
        "type": "bench",
        "x": 3320,
        "y": 2592,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_3791_1857",
        "type": "bench",
        "x": 3791,
        "y": 1857,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_4087_2179",
        "type": "bench",
        "x": 4087,
        "y": 2179,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_4102_2446",
        "type": "bench",
        "x": 4102,
        "y": 2446,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_4435_2440",
        "type": "bench",
        "x": 4435,
        "y": 2440,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_5736_1868",
        "type": "bench",
        "x": 5736,
        "y": 1868,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_5663_1390",
        "type": "bench",
        "x": 5663,
        "y": 1390,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_5574_928",
        "type": "bench",
        "x": 5574,
        "y": 928,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_4827_991",
        "type": "bench",
        "x": 4827,
        "y": 991,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_4986_1596",
        "type": "bench",
        "x": 4986,
        "y": 1596,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_4579_1302",
        "type": "bench",
        "x": 4579,
        "y": 1302,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_4530_1108",
        "type": "bench",
        "x": 4530,
        "y": 1108,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_3740_1452",
        "type": "bench",
        "x": 3740,
        "y": 1452,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_3692_1062",
        "type": "bench",
        "x": 3692,
        "y": 1062,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_3795_667",
        "type": "bench",
        "x": 3795,
        "y": 667,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_3360_768",
        "type": "bench",
        "x": 3360,
        "y": 768,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_3171_758",
        "type": "bench",
        "x": 3171,
        "y": 758,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_3154_474",
        "type": "bench",
        "x": 3154,
        "y": 474,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_3120_18",
        "type": "bench",
        "x": 3120,
        "y": 18,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_3786_327",
        "type": "bench",
        "x": 3786,
        "y": 327,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_3857_1220",
        "type": "bench",
        "x": 3857,
        "y": 1220,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_3217_1210",
        "type": "bench",
        "x": 3217,
        "y": 1210,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_2703_1223",
        "type": "bench",
        "x": 2703,
        "y": 1223,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_2000_1093",
        "type": "bench",
        "x": 2000,
        "y": 1093,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_1657_816",
        "type": "bench",
        "x": 1657,
        "y": 816,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_4856_2120",
        "type": "bench",
        "x": 4856,
        "y": 2120,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_4540_1877",
        "type": "bench",
        "x": 4540,
        "y": 1877,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_4605_1815",
        "type": "bench",
        "x": 4605,
        "y": 1815,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_2221_1195",
        "type": "bench",
        "x": 2221,
        "y": 1195,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_2311_1829",
        "type": "bench",
        "x": 2311,
        "y": 1829,
        "title": "Bench",
        "desc": ""
    },
    {
        "id": "bench_3463_982",
        "type": "bench",
        "x": 3463,
        "y": 982,
        "title": "Bench",
        "desc": ""
    },
        //Bellway:::
    {
        "id": "bellway_1603_3022",
        "type": "bellway",
        "x": 1603,
        "y": 3022,
        "title": "Bellway - The Slob",
        "desc": ""
    },
    {
        "id": "bellway_1168_2376",
        "type": "bellway",
        "x": 1168,
        "y": 2376,
        "title": "Bellway - Blasted Steps",
        "desc": ""
    },
    {
        "id": "bellway_1735_1899",
        "type": "bellway",
        "x": 1735,
        "y": 1899,
        "title": "Bellway - Shellwood",
        "desc": ""
    },
    {
        "id": "bellway_1516_1103",
        "type": "bellway",
        "x": 1516,
        "y": 1103,
        "title": "Bellway - Bone Bottom",
        "desc": ""
    },
    {
        "id": "bellway_1882_1343",
        "type": "bellway",
        "x": 1882,
        "y": 1343,
        "title": "Bellway - The Marrow",
        "desc": ""
    },
    {
        "id": "bellway_3201_1024",
        "type": "bellway",
        "x": 3201,
        "y": 1024,
        "title": "Bellway - Deep Docks",
        "desc": ""
    },
    {
        "id": "bellway_4566_1107",
        "type": "bellway",
        "x": 4566,
        "y": 1107,
        "title": "Bellway - Far Fields",
        "desc": ""
    },
    {
        "id": "bellway_4459_2438",
        "type": "bellway",
        "x": 4459,
        "y": 2438,
        "title": "Bellway - Bilewater",
        "desc": ""
    },
    {
        "id": "bellway_4859_3504",
        "type": "bellway",
        "x": 4859,
        "y": 3504,
        "title": "Bellway - Putrified Ducts",
        "desc": ""
    },
    {
        "id": "bellway_3649_2926",
        "type": "bellway",
        "x": 3649,
        "y": 2926,
        "title": "Bellway - Grand Bellway",
        "desc": ""
    },
    {
        "id": "bellway_2793_1665",
        "type": "bellway",
        "x": 2793,
        "y": 1665,
        "title": "Bellway - Bellhart",
        "desc": ""
    },
    {
        "id": "bellway_3681_1741",
        "type": "bellway",
        "x": 3681,
        "y": 1741,
        "title": "Bellway - Greymoor",
        "desc": ""
    };
    //Ventrica::
    {
        "id": "ventrica_3411_4016",
        "type": "ventrica",
        "x": 3411,
        "y": 4016,
        "title": "Ventrica Station - Terminus",
        "desc": ""
    },
    {
        "id": "ventrica_3429_3690",
        "type": "ventrica",
        "x": 3429,
        "y": 3690,
        "title": "Ventrica Station - Memorium",
        "desc": ""
    },
    {
        "id": "ventrica_3083_3462",
        "type": "ventrica",
        "x": 3083,
        "y": 3462,
        "title": "Ventrica Station - High Halls",
        "desc": ""
    },
    {
        "id": "ventrica_3836_3438",
        "type": "ventrica",
        "x": 3836,
        "y": 3438,
        "title": "Ventrica Station - First Shrine",
        "desc": ""
    },
    {
        "id": "ventrica_3735_2926",
        "type": "ventrica",
        "x": 3735,
        "y": 2926,
        "title": "Ventrica Station - Grand Bellway",
        "desc": ""
    },
    {
        "id": "ventrica_2329_2937",
        "type": "ventrica",
        "x": 2329,
        "y": 2937,
        "title": "Ventrica Station - Choral Chambers",
        "desc": ""
    },
    {
        "id": "ventrica_3110_2519",
        "type": "ventrica",
        "x": 3110,
        "y": 2519,
        "title": "Ventrica Station - Underworks",
        "desc": ""
    },
        //vendor:
         {
        "id": "vendor_1319_3021",
        "type": "vendor",
        "x": 1319,
        "y": 3021,
        "title": "Shakra - Mount Fay",
        "desc": ""
    },
    {
        "id": "vendor_972_2668",
        "type": "vendor",
        "x": 972,
        "y": 2668,
        "title": "Shakra - Sands of Karak",
        "desc": ""
    },
    {
        "id": "vendor_976_2482",
        "type": "vendor",
        "x": 976,
        "y": 2482,
        "title": "Grindle",
        "desc": ""
    },
    {
        "id": "vendor_1501_2095",
        "type": "vendor",
        "x": 1501,
        "y": 2095,
        "title": "Shakra - Blasted Steps",
        "desc": ""
    },
    {
        "id": "vendor_1018_1485",
        "type": "vendor",
        "x": 1018,
        "y": 1485,
        "title": "Shakra - Wormways",
        "desc": ""
    },
    {
        "id": "vendor_1536_1091",
        "type": "vendor",
        "x": 1536,
        "y": 1091,
        "title": "Pebb",
        "desc": ""
    },
    {
        "id": "vendor_1574_1128",
        "type": "vendor",
        "x": 1574,
        "y": 1128,
        "title": "Shakra - Bone Bottom",
        "desc": ""
    },
    {
        "id": "vendor_1728_1302",
        "type": "vendor",
        "x": 1728,
        "y": 1302,
        "title": "Shakra - The Marrow",
        "desc": ""
    },
    {
        "id": "vendor_2061_1688",
        "type": "vendor",
        "x": 2061,
        "y": 1688,
        "title": "Shakra - Shellwoods",
        "desc": ""
    },
    {
        "id": "vendor_2718_1665",
        "type": "vendor",
        "x": 2718,
        "y": 1665,
        "title": "Frey",
        "desc": ""
    },
    {
        "id": "vendor_2824_1703",
        "type": "vendor",
        "x": 2824,
        "y": 1703,
        "title": "Shakra - Bellhart",
        "desc": ""
    },
    {
        "id": "vendor_3437_1377",
        "type": "vendor",
        "x": 3437,
        "y": 1377,
        "title": "Shakra - Hunter's March",
        "desc": ""
    },
    {
        "id": "vendor_3568_1497",
        "type": "vendor",
        "x": 3568,
        "y": 1497,
        "title": "Mottled Skarr",
        "desc": ""
    },
    {
        "id": "vendor_3287_1061",
        "type": "vendor",
        "x": 3287,
        "y": 1061,
        "title": "Shakra - Deep Docks",
        "desc": ""
    },
    {
        "id": "vendor_3560_983",
        "type": "vendor",
        "x": 3560,
        "y": 983,
        "title": "Forge Daughter",
        "desc": ""
    },
    {
        "id": "vendor_3985_1337",
        "type": "vendor",
        "x": 3985,
        "y": 1337,
        "title": "Shakra - Hunter's March",
        "desc": ""
    },
    {
        "id": "vendor_4462_1046",
        "type": "vendor",
        "x": 4462,
        "y": 1046,
        "title": "Shakra - Far Fields",
        "desc": ""
    },
    {
        "id": "vendor_4587_1297",
        "type": "vendor",
        "x": 4587,
        "y": 1297,
        "title": "Mort",
        "desc": ""
    },
    {
        "id": "vendor_4619_1814",
        "type": "vendor",
        "x": 4619,
        "y": 1814,
        "title": "Shakra - Greymoor",
        "desc": ""
    },
    {
        "id": "vendor_4841_2633",
        "type": "vendor",
        "x": 4841,
        "y": 2633,
        "title": "Shakra - Bilewater",
        "desc": ""
    },
    {
        "id": "vendor_3951_3372",
        "type": "vendor",
        "x": 3951,
        "y": 3372,
        "title": "Jubilana",
        "desc": ""
    },
    {
        "id": "vendor_3396_2627",
        "type": "vendor",
        "x": 3396,
        "y": 2627,
        "title": "Twelfth Architect",
        "desc": ""
    },
    {
        "id": "vendor_4066_2179",
        "type": "vendor",
        "x": 4066,
        "y": 2179,
        "title": "Shakra - Sinner's Road",
        "desc": ""
    }
];
